### ISSUE TITLE
[Help]: Questions about FACodec's Parameter

### ISSUE THREAD

**Issue by Pydataman** [open-mmlab/Amphion#194] opened 2024-04-30 06:09 UTC
if self.use_gr_x_timbre:
            self.x_timbre_predictor = nn.Sequential(
                GradientReversal(alpha=1),
                CNNLSTM(in_channels, 245200, 1, global_pred=True),
            )

Why is there a parameter `245200` in the codes?

**Comment by HeCheng0625** [comment] 2024-05-06 06:44
This part of the parameters is used to predict the speaker id during the training process and is not used during inference. Please ignore it.

**Comment by Pydataman** [comment] 2024-05-06 09:11
> This part of the parameters is used to predict the speaker id during the training process and is not used during inference. Please ignore it.

@HeCheng0625 
that means there were 245200 speakers during training？

**Comment by jiaqili3** [comment] 2024-07-18 15:54
Hi, we're closing this thread since the question about number of speakers in FACodec training is not directly related to this repo, for more detailed training we recommend looking at the latest FACodec reproduce in latest Amphion release (currently in pr). Thanks!

**Closed by jiaqili3** 2024-07-18 15:54 UTC
